version: "3.9"

services:
  hydrabase:
    build: app
    ports:
      - "8080:8080"
    networks:
      - hydra-net
    volumes:
      - persist:/app
  pyexporter:
    build: exporter
    ports:
      - "8600:8600"
    networks:
      - hydra-net
    depends_on:
      - hydrabase
    volumes:
      - persist:/pyexp
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - pyexporter
    networks:
      - hydra-net
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - hydra-net

volumes:
  persist:
  grafana-storage:

networks:
  hydra-net:
